Add Anmeldung bot, Hypofriend bot
conradkirschner/awesome-bots-berlin pull request #3
Opened 2024-02-21 04:29 UTC by nicbou

2024-03-01 20:26 UTC, conradkirschner requested changes

2024-03-01 20:26 UTC, conradkirschner commented on README.md
> +- [Hypofriend Telegram bot](https://hypofriend.de/en/lp/immofriend)
Here I don't see any source code, therefore I would not put it in the list.

2024-03-01 20:27 UTC, conradkirschner requested changes

2024-03-01 20:27 UTC, conradkirschner commented on README.md
> +- [Hypofriend Telegram bot](https://hypofriend.de/en/lp/immofriend)
```suggestion
```

2024-03-01 20:28 UTC, conradkirschner commented
Thanks for contribution <3 ! 

After removing the one I would merge it :)

2024-03-02 01:46 UTC, nicbou commented
Done!

2024-03-02 22:22 UTC, conradkirschner approved these changes

2024-03-02 22:23 UTC, merged